version: "3"
services:
    docker:
        image: docker:dind
        privileged: yes
        environment:
            DOCKER_TLS_CERTDIR: ""
    viky-app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DOCKER_HOST: tcp://docker:2375
        depends_on:
            - docker
        ports:
            - "3000:3000"
